### ISSUE TITLE
展示多个文本的时候只能展示一个

### ISSUE THREAD

**Issue by GeniusMK2** [bytelang/kplayer-go#117]
文档没有写怎样展示多个文本，以及调整多个文本的位置
而且貌似文本长度有限制

**Comment by GeniusMK2** [comment]
知道原因了，因为百分号的问题
现在百分号不能正常显示

**Comment by vaptu** [comment]
%因为是特殊字符，还未对这类符号进行转移。当前需要自己转义，可以尝试使用`\%`来显示百分号。

展示多个文本，可以添加多个show-text插件来实现。或者使用空格以及\n来进行换行
