### ISSUE TITLE
core shut down success

### ISSUE THREAD

**Issue by Gao-yu-1214** [bytelang/kplayer-go#120]
ERRO[2023-07-14 00:51:35] core return error                             code=-1094995529 error="decode failed. file path: /root/kplayer/football/01.mp4. error: Invalid data found when processing input [-1094995529]. file: codec/KPDecode.cpp. line: 181"
INFO[2023-07-14 00:51:35] core shut down success

推流过程中报错

**Comment by vaptu** [comment]
尝试把出错误的视频文件使用转码工具重编码一次。推荐使用h264/aac的编码方式

**Comment by Gao-yu-1214** [comment]
> 尝试把出错误的视频文件使用转码工具重编码一次。推荐使用h264/aac的编码方式

厉害，就是这个原因，现在可以正常播放了👍
