### ISSUE TITLE
希望可以让项目可以编译，以便项目更好的发展壮大

### ISSUE THREAD

**Issue by chekun** [bytelang/kplayer-go#25]
作者您好，目前本项目仅仅作为一个wrapper开源出来，无法本地编译跑起来，希望可以将闭源的部分通过某种方式开放出来，让项目可以跑起来，这样才能更好的让大家参与项目进来，辛苦，谢谢🙏

**Comment by bytelang** [comment]
好的，后续将会提供可供编译的库

**Comment by lincoln314** [comment]
> 好的，后续将会提供可供编译的库

作者您好，什么时候能开放所有的库呢，谢谢~
