### ISSUE TITLE
您好，帮忙看看这个问题 knock failed .cannot connection api server on max retries

### ISSUE THREAD

**Issue by lincoln314** [bytelang/kplayer-go#29]
您好，帮忙看看这个问题，每次调用rpc接口，大概持续35分钟后，就报这个错，请问是否做了时间限制呢？静候您的回复，谢谢。

**Comment by bytelang** [comment]
好的，rpc接口正在做稳定性测试。将会不在不久后退出新版本来提高接口的可用性和易用性

**Comment by lincoln314** [comment]
> 好的，rpc接口正在做稳定性测试。将会不在不久后退出新版本来提高接口的可用性和易用性

看了下开源出来的代码，应该是你再代码中做了限制吧，只能使用36分钟。代码如下。
因为没提供完整的源码，我这边无法编译，能否提供去除限制的版本用于测试呢？非常感谢。
![image](https://user-images.githubusercontent.com/49439483/177257696-86892cee-0399-4abb-923c-a5d883b85d2e.png)

**Comment by vaptu** [comment]
这里是程序定时器对API Server的心跳检测，防止程序运行中对插件与资源的增加无法获取正确的插件资源。如果频繁发生这类错误请检查服务器能不能与API服务正常通信
```shell
curl -vvI https://v2api.kplayer.bytelang.cn
```

当前程序运行期间无法连接API Server是会造成程序中途中断。

**Comment by vaptu** [comment]
或者通过telnet检查服务器是否可以正常与`v2api.kplayer.bytelang.cn`的443端口正常通信

**Comment by lincoln314** [comment]
谢谢解答，在网络正常的情况下，可以正常运行。
