### ISSUE TITLE
建议增加仅使用缓存即可播放功能

### ISSUE THREAD

**Issue by mvfeng** [bytelang/kplayer-go#44]
看了下，感觉kplay最大的优势对于我这样的个人玩家来说(一般低配服务器)，最喜欢缓存推流不占用CPU和内存性能特点，低配服务器一般存储空间也低哈哈，如果可以直接用缓存播放（可以删除原视频前提），极大的提高磁盘空间播放使用效率，强烈建议出一个这样的功能！

**Comment by vaptu** [comment]
好的，这个功能是在计划范围内。由于这版本存在问题导致不可用，下版本修复

**Comment by vaptu** [comment]
v0.5.8已修复
