### ISSUE TITLE
资源设置的问题

### ISSUE THREAD

**Issue by mirror222** [bytelang/kplayer-go#45]
请问如何用MP3 列表作为背景音乐，通过API 切换图片作为直播的内容呢？

如果是静态资源可以这样配置：

"groups": [
          {
            "path": "/home/user/video/background.png",
            "media_type": "video",
            "persistent_loop": true
          },
          {
            "path": "/home/user/video/music.mp3",
            "media_type": "audio"
          }
        ]
感谢。

**Comment by mirror222** [comment]
找到了。谢谢

**Comment by vaptu** [comment]
混合资源当前没有针对group单独更新的API，现在只支持更新整个groups组的资源。
当前的功能如果想要可以动态控制展示图片，可以尝试把mp3压制成黑色背景的视频资源。配合show-media或show-image插件来实现动态更新图片

**Comment by mirror222** [comment]
感谢。

**Comment by mirror222** [comment]
> 

请问，我是了一下，有点卡顿，如果用缓存很就没事。
我的服务器是2核4G 的LINODE服务器，请问推荐多少核比较好呢？

**Comment by vaptu** [comment]
> > 
> 
> 请问，我测试了一下，我的服务器是2核4G 的LINODE服务器，有点卡顿，如果用缓存很流畅。 ，能否推荐一下配置？

因为原视频资源的质量和具体网络带宽情况影响，这个没有推荐配置。需要自己根据机器配置来进行参数调优。如果使用的图片+音频的情况，请参数这里的提醒来降低卡顿的情况

<img width="934" alt="image" src="https://user-images.githubusercontent.com/13956208/200307267-e62df70a-1adf-4649-811e-99aa09431e34.png">


[https://docs.kplayer.net/v0.5.7/config/resource.html](https://docs.kplayer.net/v0.5.7/config/resource.html)
