### ISSUE TITLE
不转码纯推流模式

### ISSUE THREAD

**Issue by leim** [bytelang/kplayer-go#49]
建议，可以做一个纯推流模式，不对音视频资源做任何转码操作，这样应该可以降低不少服务器负载（其实这样和缓存模式差不多，只不过这样可以更方便的供用户按照自己的需求生成对应的音视频资源）

纯推流模式也可以不加载插件，不对音视频做任何二次加工（包括但不限于加图片、文本、时间戳、进度条等等）。

感谢大佬。

**Comment by vaptu** [comment]
上面描述的场景就是kplayer缓存的设计，不再二次编解码来降低CPU和内存的占用量。

为了保证不同视频资源在相同一致的编码输出参数来保证不出错误不断流的推流，所以kplayer会首先做一次编解码的操作来保证和预期推流的视频参数一致。

如果首次运行CPU占用过高，可以使用预生成缓存的方式来生成完毕缓存再进行推流。

```shell
./kplayer play start -g
```

> 例如如果不重新编码的情况下是无法对720p、1080p的两个不同参数资源不建立重新的rtmp链接来完成无缝推流。它会造成音画不同步、绿屏等
