### ISSUE TITLE
运行MP3链接到一半就错误（code=-110；error=decode failed.）了

### ISSUE THREAD

**Issue by TXIuTnVsbA** [bytelang/kplayer-go#53]
我是用docker的，好不容易开发了网易云点歌工具= =然后发现每次都是运行到一半就出现错误。具体错误信息如下：

ERRO[2022-12-18 16:49:00] core return error                             code=-110 error="decode failed. file path: http://m701.music.126.net/20221219010741/76226bd3ae41d37386681a767592614f/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/15893871801/89ff/62da/120b/e2f07a40b4c1e23f0dc1305087cc8976.mp3. error: Operation timed out [-110]. file: codec/KPMix.cpp. line: 147"

我也不知道是不是网易云的问题，但是我自己用浏览器去下载或者试听都没有断流这个问题

**Comment by vaptu** [comment]
这个错误看起来是打开并下载mp3资源连接超时导致的，如果你是用程序来编码解析的。你可以再传参给kplayer之前获取下资源的响应状态是否为200来确保资源是可用的。或者先使用debug的方式把资源提前下载到本地来排查出是资源本身的问题还是kplayer的问题

**Comment by TXIuTnVsbA** [comment]
> 

OK谢谢。

**Comment by TXIuTnVsbA** [comment]
> 这个错误看起来是打开并下载mp3资源连接超时导致的，如果你是用程序来编码解析的。你可以再传参给kplayer之前获取下资源的响应状态是否为200来确保资源是可用的。或者先使用debug的方式把资源提前下载到本地来排查出是资源本身的问题还是kplayer的问题

OK谢谢。
