### ISSUE TITLE
请使用不超过 4 秒的关键帧频率

### ISSUE THREAD

**Issue by 863zq** [bytelang/kplayer-go#55]
YT直播，分辨率设置1080P，然后提示这个“请使用不超过 4 秒的关键帧频率”
应该需要改什么参数啊？

**Comment by vaptu** [comment]
当前还未支持关键帧相关参数设置

**Comment by vaptu** [comment]
v0.5.8版本已缩短关键帧的最大时间间隔，请尝试看能不能解决问题

**Comment by 863zq** [comment]
多谢，问题已经解决了
