### ISSUE TITLE
报错 output add failed. error: Connection refused [-111] 

### ISSUE THREAD

**Issue by zhenhappy** [bytelang/kplayer-go#56]
config.json

```
{
    "version": "2.0.0",
    "resource": {
        "lists": [
            "/video/example_1.mp4",
            "/video/example_2.mp4"
        ]
    },
    "output": {
        "lists": [
            {
                "path": "rtmp://127.0.0.1:1935/push"
            }
        ]
    }
}
```

docker命令
docker run --rm -it --name kplayer -p 1935:1935 -v $PWD/video:/video -v $PWD/config.json:/kplayer/config.json bytelang/kplayer:latest

log
![CleanShot 2023-01-04 at 15 09 34](https://user-images.githubusercontent.com/9161946/210502174-20104e91-e1d1-46fb-92ae-d2f0255a7fa7.png)

**Comment by vaptu** [comment]
output path 推流地址需要一个可用的推流地址

**Comment by maozhuoyuan** [comment]
> output path 推流地址需要一个可用的推流地址

我是按照[这篇文章](https://blog.csdn.net/qq_40167860/article/details/122812137)来做的本地用ffmpeg可以推流到服务上去用kplayer不行 kplayer也是docker里的 两个在同一个网络下
