### ISSUE TITLE
【BUG】 推流有报错 output add failed. error: I/O error [-5]      error="I/O error [-5]"

### ISSUE THREAD

**Issue by FlechazoPh** [bytelang/kplayer-go#59]
环境：
``
root@instance:/home/Scripts/KPlayer/kplayer# ./kplayer play start

kplayer for golang v0.5.7 Copyright(c) 2019-2022 the ByteLang Studio (https://kplayer.bytelang.cn)
  libkplayer version: v1.5.2 plugin version: 1.5.1 license version: v1
  toolchains GNU(10.3.1) C++ Standard 17 on Linux-aarch64-4.18.0-193.28.1.el7.aarch64
  build with build-chains cmake(3.21.3) type with Release
  Hope you have a good experience.

``
报错日志：

``

 output add failed. error: I/O error [-5]      error="I/O error [-5]"

``

![image](https://user-images.githubusercontent.com/94276146/211843718-72db5388-b981-4ac1-bf41-96f52f365edf.png)

**Comment by vaptu** [comment]
1. 刷新页面并检查直播间是不是正常开启状态
2. 排查服务器IP地址是不是为中国香港、中国台湾和国外IP地址，bilibili服务端会拒绝此类IP地址的连接

**Comment by FlechazoPh** [comment]
> * 刷新页面并检查直播间是不是正常开启状态
> * 排查服务器IP地址是不是为中国香港、中国台湾和国外IP地址，bilibili服务端会拒绝此类IP地址的连接

可能是因为国外地址导致的

**Comment by abigmiu** [comment]
![image](https://user-images.githubusercontent.com/43983920/229263341-2d694619-d6df-42b8-82e1-4986c95da8b5.png)
我服务器是国内的也报这个错。

**Comment by Cmyini** [comment]
内蒙古服务器也一样报错ERRO[2023-07-30 05:17:04] output add failed. error: I/O error [-5]

**Comment by superHao2000** [comment]
> 内蒙古服务器也一样报错ERRO[2023-07-30 05:17:04] output add failed. error: I/O error [-5]

我也是
