### ISSUE TITLE
bilibili无法打开输出流

### ISSUE THREAD

**Issue by ailachan** [bytelang/kplayer-go#60]
[pid:13128/tid:13137] [2023-01-24 23:37:19.910] [KPEncode] [error] 无法打开输出流; path: rtmp://live-push.bilivideo.com/live-bvc/?streamname=live_49837660_3234682&key=031384bb82837f2176376574dcb1c8bd&schedule=rtmp&pflag=1; error: Input/output error [-5]
[pid:13128/tid:13137] [2023-01-24 23:37:19.910] [KPSingleOutput] [error] 初始化输出器失败; code: -5
[pid:13128/tid:13137] [2023-01-24 23:37:19.912] [KPSingleOutput] [warning] 无法连接到流媒体服务器或打开目标文件，5秒后将再次重试连接

**Comment by ailachan** [comment]
老版本新版本都试过了,都是这样

**Comment by a1667834841** [comment]
是不是配置错了 我试了可以

**Comment by ailachan** [comment]
> 是不是配置错了 我试了可以

你的配置发过来看看可以吗,我在想是不是因为我服务器在国外的原因

**Comment by a1667834841** [comment]
{
    "version": "2.0.0",
    "resource": {
        "lists": [
	        	{
        			"path": "/opt/shell/video/b站/"
	        	}
			
		],
		"extensions": [ "mp4", "flv" ]
    },
    "output": {
    	   "reconnect_internal": 5,
        "lists": [
            {
                "path": "rtmp://live-push.bilivideo.com/live-bvc/?xxxx"
            }
        ]
    },

    "play": {
	    "cache_on": true,
	     "encode": {
		      "video_width": 854,
		      "video_height": 480,
		      "video_fps": 25,
		      "audio_channel_layout": 3,
		      "audio_sample_rate": 44100,
		      "bit_rate": 0,
		      "avg_quality": 0
		    }
	  },

    "plugin": {
	    "lists": [
	      {
	        "path": "show-text",
	        "params": {
	          "text": "放下手机\n\r倾听五分钟音乐",
	          "fontsize": "20",
	          "fontcolor": "white",
	          "x": 10,
		     "y": 410
	       }
	       }
    ]
  }
}

**Comment by a1667834841** [comment]
> > 是不是配置错了 我试了可以
> 
> 你的配置发过来看看可以吗,我在想是不是因为我服务器在国外的原因

`{
    "version": "2.0.0",
    "resource": {
        "lists": [
	        	{
        			"path": "/opt/shell/video/b站/"
	        	}
			
		],
		"extensions": [ "mp4", "flv" ]
    },
    "output": {
    	   "reconnect_internal": 5,
        "lists": [
            {
                "path": "rtmp://live-push.bilivideo.com/live-bvc/?streamname=live_316654429_34189299&key=ff1a57a9eadee685bd60e3dcf947d30e&schedule=rtmp&pflag=1"
            }
        ]
    },

    "play": {
	    "cache_on": true,
	     "encode": {
		      "video_width": 854,
		      "video_height": 480,
		      "video_fps": 25,
		      "audio_channel_layout": 3,
		      "audio_sample_rate": 44100,
		      "bit_rate": 0,
		      "avg_quality": 0
		    }
	  },

    "plugin": {
	    "lists": [
	      {
	        "path": "show-text",
	        "params": {
	          "text": "放下手机\n\r倾听五分钟音乐",
	          "fontsize": "20",
	          "fontcolor": "white",
	          "x": 10,
		     "y": 410
	       }
	       }
    ]
  }
}
`

**Comment by a1667834841** [comment]
> > 是不是配置错了 我试了可以
> 
> 你的配置发过来看看可以吗,我在想是不是因为我服务器在国外的原因

```json
{
    "version": "2.0.0",
    "resource": {
        "lists": [
	        	{
        			"path": "/opt/shell/video/b站/"
	        	}
			
		],
		"extensions": [ "mp4", "flv" ]
    },
    "output": {
    	   "reconnect_internal": 5,
        "lists": [
            {
                "path": "rtmp://live-push.bilivideo.com/live-bvc/?streamname=live_316654429_34189299&key=ff1a57a9eadee685bd60e3dcf947d30e&schedule=rtmp&pflag=1"
            }
        ]
    },

    "play": {
	    "cache_on": true,
	     "encode": {
		      "video_width": 854,
		      "video_height": 480,
		      "video_fps": 25,
		      "audio_channel_layout": 3,
		      "audio_sample_rate": 44100,
		      "bit_rate": 0,
		      "avg_quality": 0
		    }
	  },

    "plugin": {
	    "lists": [
	      {
	        "path": "show-text",
	        "params": {
	          "text": "放下手机\n\r倾听五分钟音乐",
	          "fontsize": "20",
	          "fontcolor": "white",
	          "x": 10,
		     "y": 410
	       }
	       }
    ]
  }
}

```

**Comment by a1667834841** [comment]
> > 是不是配置错了 我试了可以
> 
> 你的配置发过来看看可以吗,我在想是不是因为我服务器在国外的原因

```json
{
    "version": "2.0.0",
    "resource": {
        "lists": [
	        	{
        			"path": "/opt/shell/video/b站/"
	        	}
			
		],
		"extensions": [ "mp4", "flv" ]
    },
    "output": {
    	   "reconnect_internal": 5,
        "lists": [
            {
                "path": "rtmp://live-push.bilivideo.com/live-bvc/?xxxx"
            }
        ]
    },

    "play": {
	    "cache_on": true,
	     "encode": {
		      "video_width": 854,
		      "video_height": 480,
		      "video_fps": 25,
		      "audio_channel_layout": 3,
		      "audio_sample_rate": 44100,
		      "bit_rate": 0,
		      "avg_quality": 0
		    }
	  },

    "plugin": {
	    "lists": [
	      {
	        "path": "show-text",
	        "params": {
	          "text": "放下手机\n\r倾听五分钟音乐",
	          "fontsize": "20",
	          "fontcolor": "white",
	          "x": 10,
		     "y": 410
	       }
	       }
    ]
  }
}

```

**Comment by it985** [comment]
[issues59](https://github.com/bytelang/kplayer-go/issues/59)

**Comment by ailachan** [comment]
> [issues59](https://github.com/bytelang/kplayer-go/issues/59)

啊这还真是,完犊子了

**Comment by it985** [comment]
> > [issues59](https://github.com/bytelang/kplayer-go/issues/59)
> 
> 啊这还真是,完犊子了

其他平台应该没有限制

**Comment by ailachan** [comment]
> > > [issues59](https://github.com/bytelang/kplayer-go/issues/59)
> > 
> > 
> > 啊这还真是,完犊子了
> 
> 其他平台应该没有限制

行吧，不过还是谢谢啦
