### ISSUE TITLE
http api 错误

### ISSUE THREAD

**Issue by changyuwu** [bytelang/kplayer-go#61]
curl -X "GET" "http://127.0.0.1:4156/resource/list" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{}'
报这个错误，
{"InternalCode":14,"Message":"rpc error: code = Unavailable desc = failed to receive server preface within timeout","Details":[]}#

启动时显示http 和  grpc server已经启动
-> # ./kplayer play start
kplayer for golang v0.5.7 Copyright(c) 2019-2022 the ByteLang Studio (https://kplayer.bytelang.cn)
  libkplayer version: v1.5.2 plugin version: 1.5.1 license version: v1 
  toolchains GNU(10.3.1) C++ Standard 17 on Linux-x86_64-5.18.14-arch1-1
  build with build-chains cmake(3.21.3) type with Release
  Hope you have a good experience.
---------------------------------------------------------------------------------------------------
INFO[2023-01-29 16:20:10] grpc server listening                         address=0.0.0.0 port=4155
INFO[2023-01-29 16:20:10] http server listening                         address=0.0.0.0 port=4156
下面是相关的配置
"play": {
    "play_model": "loop",
    "cache_on": true,
    "cache_uncheck": true,
    "skip_invalid_resource": true,
    "rpc": {
      "on": true,
      "http_port": 4156,
      "grpc_port": 4155,
      "address": "0.0.0.0"
    },
    "encode":{
      "video_width": 854,
      "video_height": 480,
      "video_fps": 25,
      "audio_channel_layout": 3,
      "audio_sample_rate": 44100,
      "bit_rate": 0,
      "avg_quality": 0
    }
  }

**Comment by stanle1** [comment]
同问？
