### ISSUE TITLE
resource使用frp源解析错误

### ISSUE THREAD

**Issue by LkingH** [bytelang/kplayer-go#64]
![image](https://user-images.githubusercontent.com/39640500/219959172-a3e04d2d-2d0b-4324-9ca5-2e4e53324520.png)
![WTTXX)Q)FQR_GHXGO@LC($X](https://user-images.githubusercontent.com/39640500/219959184-638890cb-8f35-4761-a3b5-5baf5de2c34f.png)
配置和报错见上图所示，请问有使用ftp源成功的大佬吗，麻烦指点一下，谢谢！

**Comment by LkingH** [comment]
试了下，指定文件可以播放。
指定文件夹就出现上述错误

**Comment by vaptu** [comment]
文件夹模式下仅支持本地文件的方式，网络协议还未能支持读取FTP的文件夹功能。

**Comment by LkingH** [comment]
@vaptu Got it, thanks for your reply !
