### ISSUE TITLE
请问在docker版本中如何添加插件

### ISSUE THREAD

**Issue by sanwecn** [bytelang/kplayer-go#73]
如题，感谢。

**Comment by vaptu** [comment]
在kplayer.net文档中的插件均可以直接配置使用，在config.jso或者config.yaml中按照格式配置插件即可直接使用

**Comment by sanwecn** [comment]
![QQ截图20230315163547](https://user-images.githubusercontent.com/101993515/225254719-0f572254-c267-4da0-9e94-458726bf2828.png)
![QQ截图20230315163513](https://user-images.githubusercontent.com/101993515/225254729-7731a94b-7793-4989-84c2-e8c25a380c68.png)
是我配置出错了吗？

**Comment by sanwecn** [comment]
> 在kplayer.net文档中的插件均可以直接配置使用，在config.jso或者config.yaml中按照格式配置插件即可直接使用

![QQ截图20230315163547](https://user-images.githubusercontent.com/101993515/225254979-c9008300-a0f2-4570-ba6a-e8fd3019a34b.png)
![QQ截图20230315163513](https://user-images.githubusercontent.com/101993515/225255008-da445558-08c0-4d3a-ae2b-b736aa842029.png)

是我配置出错了吗？

**Comment by vaptu** [comment]
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/13956208/225255204-5337a7a5-005f-4034-b570-465b87e68da5.png">

参考 unique 使用方法
