### ISSUE TITLE
cannot access api

### ISSUE THREAD

**Issue by blakeyi** [bytelang/kplayer-go#77]
![image](https://user-images.githubusercontent.com/20620315/227269673-5cd0be8c-b3b6-4d6c-8221-e9674c11fabd.png)

**request**:curl "http://127.0.0.1:4156/resource/current"      -H 'Content-Type: application/json; charset=utf-8'      -d $'{}'
**the result as follow**:
{"InternalCode":12,"Message":"rpc error: code = Unimplemented desc = Method Not Allowed","Details":[]}

all api has same problem

**the config as follow:**
    "version": "2.0.0",
    "resource": {
        "lists": [
            "./video/"
        ]
    },
    "play": {
        "play_model": "loop",
        "cache_on": true,
        "rpc": {
            "on": true,
            "http_port": 4156,
            "grpc_port": 4157,
            "address": "0.0.0.0"
        }
   kplayer version:
![image](https://user-images.githubusercontent.com/20620315/227271368-46b1a3e0-9aa0-483a-aee4-217f8dc40bb6.png)

**Comment by blakeyi** [comment]
need use post

**Comment by idiomer** [comment]
try use -XGET
